### PR TITLE
add bash install.sh/uninstall.sh

### PR DESCRIPTION
**Pull request by treellama**
This adds basic install/uninstall scripts, in case packages aren't available for the distro/arch. I figured bash would be a good choice, since the rest is written in bash.

### CODE REVIEW

**Comment by alexmyczko** [comment]
Thanks for the PR, but these scripts will fail on macOS, installation and removal should be done with a Makefile, targets are usually install: and uninstall:

But since configuration can be defaults, and the client now can be run as user only, I can and will not accept this pull request.

I did consider rewriting this in golang, C, or Objective-C, but the decision is still open.

**Comment by treellama** [comment]
The first install I used for script for was for an older arm7 raspberry pi; the available deb is only arm64. I also have one running netbsd as well. And I use macports instead of  homebrew on macOS. 

I think it would be good to have _some_ way to install without manually copying files. I could write a Makefile if you're interested. A user install could be accomplished by setting environment variables and/or using a different target.

**Comment by alexmyczko** [comment]
The debian source package can be found here: https://salsa.debian.org/debian/ruptime

```
gbp clone https://salsa.debian.org/debian/ruptime
cd ruptime
gbp export-orig
debuild
```

I would much rather prefer netbsd ports and macports version of the packaging :)

**Comment by alexmyczko** [comment]
meanwhile: https://buildd.debian.org/status/package.php?p=ruptime&suite=sid

**Pull request closed without merging**
